src/pysdjango/users_app/urls.py
"""	User application URL Configuration
	The URL configuration for the user application.
"""

# =============================================================================
# 1 | Document Metadata
# =============================================================================
__author__    = 'Lennard Streat'
__copyright__ = 'Network of Intel African Americans 2019, PyStockAnalyze Project'
__credits__   = ['Lennard Streat', 'Princton Brennan']
__license__   = 'MIT'
__version__   = '1.0'
__email__     = 'nia.stem.club'

# =============================================================================
# 2 | Imports
# =============================================================================
from django.urls import path
from . import views

# Support for serving static image files
from django.conf import settings
from django.conf.urls.static import static

# =============================================================================
# 3 | Define URLConf
# =============================================================================
# Application namespace
app_name = 'users_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('', views.temp_home, name='user-home'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

src/pysdjango/users_app/models.py
from django.db import models

# Create your models here.
class UProfile (models.Model):
	organization = models.CharField(max_length=100)
	date = models.DateTimeField(auto_now_add=True)
	image = models.ImageField(upload_to="media", default="empty")
	# List of field types:
	# https://www.webforefront.com/django/modeldatatypesandvalidation.html

	# To make a new model:
	# [1] Add to the models.py
	# [2] python manage.py makemigrations
	# [3] python manage.py migrate


class UserProfile(models.Model):
	name = models.CharField(max_length=100)
	age = models.IntegerField()
	email = models.CharField(max_length=100)
	

src/pysdjango/users_app/views.py
"""	User Application View
	Serves the HTTP response content to the requesting client.
"""

# =============================================================================
# 1 | Document Metadata
# =============================================================================
__author__    = 'Lennard Streat'
__copyright__ = 'Network of Intel African Americans 2019, PyStockAnalyze Project'
__credits__   = ['Lennard Streat', 'Princton Brennan']
__license__   = 'MIT'
__version__   = '1.0'
__email__     = 'nia.stem.club'

# =============================================================================
# 2 | Imports
# =============================================================================
# DJango imports
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm

from django.contrib import messages
	# mesages.debug
	# messages.info
	# messages.success
	# messages.warning
	# messages.error

# =============================================================================
# 3 | Registration View
# =============================================================================
def register(request):
	form = None

	if request.method == 'GET':
		form = UserCreationForm()
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save() # TODO: Research DJango security features
			username = form.cleaned_data.get('username')
			messages.success(request, f'Account created for {username}!') # Note f string usage
			# Redirect to another page to prevent multiple re-submission of form
			return redirect('users_app:user-home')

	return render(request, 'users_app/register.html', {'form' : form})

def temp_home(request):
	return render(request, 'users_app/base.html')

src/pysdjango/users_app/templates/users_app/base.html
<!DOCTYPE>
<html>
<head>
	<meta charset="utf-8" />
	<title>User Registration</title>
</head>

<body>
	<h1>PyStockAnalyze</h1>
	<div class="col-md-8">
	{% if messages %}
		{% for message in messages %}
			<div class="alert alert-{{ message.tags }}">
				{{ message }}
			</div>
		{% endfor %}
	{% endif %}
	</div>

	{% block content %}
	<a href="{% url 'users_app:register' %}">Go To Registration</a>
	{% endblock content %}
</body>
</html>

src/pysdjango/users_app/templates/users_app/register.html
{% extends "users_app/base.html" %}

{% block content %}
<div class="content-section">
	<form method="POST">
		{% csrf_token %}

		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Join Today</legend>
			{{ form.as_p }}
		</fieldset>
		<div class="form-group">
			<button class="btn btn-outline-info" type="submit">Sign Up</button> 
		</div>
	</form>

	<div class="border-top pt-3">
		<small class="text-muted">
			Already Have An Account?
			<a class="ml-2" href="#">Sign In</a>
		</small>
	</div>
</div>
{% endblock content %}